port bootstrap script to sh

diff --git a/lokinet-bootstrap b/lokinet-bootstrap
--- a/lokinet-bootstrap
+++ b/lokinet-bootstrap
@@ -5,4 +5,4 @@
 
 if [ "X$1" = "X" ] ; then url="https://i2p.rocks/i2procks.signed" ; else url="$1" ; fi
 echo "downloading $url"
-wget -O $HOME/.lokinet/bootstrap.signed "$url" &> /dev/null || echo "failed to download bootstrap from $url"
+wget -O $HOME/.lokinet/bootstrap.signed "$url" || echo "failed to download bootstrap from $url"
